### ISSUE TITLE
How can I add a fingerprint to a user ?

### ISSUE THREAD

**Issue by alexisRojas99** [coding-libs/zkteco-js#2]
Hi.

I have been using this library but I don't see a way to add a fingerprint.

would you like to help me with that ?

regards.

**Comment by anwarx4u** [comment]
@alexisRojas99 

I haven't tried this approach myself, but I believe it should work. You can use executeCmd() as follows (not tested):

```
const data = fingerprintdata; // usually should be an array

for (const [finger, item] of Object.entries(data)) {
    try {
        await zkInstance.executeCmd(10, item);
        console.log('Command executed successfully');
    } catch (error) {
        console.error('Error executing command:', error);
    }
}
```


Feel free to send a PR if you make any improvements!"
